kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

steps:
  - name: buildLib
    image: swift:latest
    commands:
      - cd Sources/Connect4Lib 
      - swift build

  - name: buildApp
    image: swift:latest
    commands:
      - cd Sources/Connect4App
      - swift build

  - name: tests
    image: swift:latest
    commands:
      - cd Sources/Connect4Lib 
      - swift test
    depends_on: [buildLib,buildApp]